volumes:
  postgres_data:
  keycloak-db-volume: {}
  redis_data:
  minio_data: {}

services:
  postgres:
    image: postgres:latest
    container_name: postgres_is
    environment:
      POSTGRES_USER: is
      POSTGRES_PASSWORD: is
      POSTGRES_DB: is
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_is
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  minio:
    image: minio/minio:latest
    container_name: minio_is
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - '9000:9000'
    volumes:
      - minio_data:/data
    command: server /data
    restart: always
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: app_container
#    environment:
#      DB_URL: jdbc:postgresql://postgres:5432/is
#      DB_USER: is
#      DB_PASSWORD: is
#      REDIS_HOST: redis
#      REDIS_PORT: 6379
#      MINIO_ENDPOINT: minio_is:9000
#      MINIO_ACCESS_KEY: minioadmin
#      MINIO_SECRET_KEY: minioadmin
#    ports:
#      - '2580:2580'
#    depends_on:
#      - postgres
#      - redis
#      - minio