volumes:
  postgres_data:
  keycloak-db-volume: {}
  redis_data:

services:
  postgres:
    image: postgres:latest
    container_name: postgres_is
    environment:
      POSTGRES_USER: is
      POSTGRES_PASSWORD: is
      POSTGRES_DB: is
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_is
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes